// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eaconnproto.proto

/*
Package eaconnproto is a generated protocol buffer package.

It is generated from these files:
	eaconnproto.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	Config
	Ack
*/
package eaconnproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Config struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Config) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type Ack struct {
	Valid string `protobuf:"bytes,1,opt,name=valid" json:"valid,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Ack) GetValid() string {
	if m != nil {
		return m.Valid
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "eaconnproto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "eaconnproto.HelloReply")
	proto.RegisterType((*Config)(nil), "eaconnproto.Config")
	proto.RegisterType((*Ack)(nil), "eaconnproto.Ack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/eaconnproto.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eaconnproto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eaconnproto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eaconnproto.proto",
}

// Client API for Publisher service

type PublisherClient interface {
	SendConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Ack, error)
}

type publisherClient struct {
	cc *grpc.ClientConn
}

func NewPublisherClient(cc *grpc.ClientConn) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) SendConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/eaconnproto.Publisher/SendConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Publisher service

type PublisherServer interface {
	SendConfig(context.Context, *Config) (*Ack, error)
}

func RegisterPublisherServer(s *grpc.Server, srv PublisherServer) {
	s.RegisterService(&_Publisher_serviceDesc, srv)
}

func _Publisher_SendConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SendConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eaconnproto.Publisher/SendConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SendConfig(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eaconnproto.Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfig",
			Handler:    _Publisher_SendConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eaconnproto.proto",
}

func init() { proto.RegisterFile("eaconnproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x1b, 0xfe, 0x34, 0xed, 0xc1, 0x00, 0x07, 0x12, 0x25, 0x30, 0x20, 0x0f, 0x08, 0x96,
	0x0c, 0x45, 0x48, 0x8c, 0x24, 0x08, 0x81, 0xc4, 0x12, 0xb5, 0x9f, 0xc0, 0x4d, 0xaf, 0xc1, 0xaa,
	0x63, 0x1b, 0x3b, 0x45, 0xe4, 0xdb, 0x23, 0xdc, 0x14, 0xb9, 0x52, 0x17, 0xeb, 0xde, 0xcf, 0xef,
	0x4e, 0xef, 0xc1, 0x29, 0xf1, 0x52, 0x2b, 0x65, 0xac, 0x6e, 0x74, 0xea, 0x5f, 0x3c, 0x0a, 0x10,
	0x63, 0x70, 0xfc, 0x4e, 0x52, 0xea, 0x09, 0x7d, 0xad, 0xc8, 0x35, 0x88, 0x70, 0xa0, 0x78, 0x4d,
	0xa3, 0xe8, 0x26, 0xba, 0x1b, 0x4e, 0xfc, 0xcc, 0x6e, 0x01, 0x3a, 0x8f, 0x91, 0x2d, 0x8e, 0x20,
	0xae, 0xc9, 0x39, 0x5e, 0x6d, 0x4c, 0x1b, 0xc9, 0x9e, 0xa0, 0xff, 0xa2, 0xd5, 0x42, 0x54, 0xbb,
	0xae, 0x60, 0x02, 0x83, 0x85, 0x90, 0xe4, 0xf9, 0x9e, 0xe7, 0xff, 0x9a, 0x5d, 0xc1, 0x7e, 0x56,
	0x2e, 0xf1, 0x1c, 0x0e, 0xbf, 0xb9, 0x14, 0xf3, 0x6e, 0x6f, 0x2d, 0xc6, 0x1f, 0x10, 0xbf, 0x59,
	0xa2, 0x86, 0x2c, 0x3e, 0xc3, 0x60, 0xca, 0x5b, 0x1f, 0x06, 0x2f, 0xd3, 0xb0, 0x5a, 0x58, 0x22,
	0xb9, 0xd8, 0xf5, 0x65, 0x64, 0xcb, 0x7a, 0xe3, 0x1c, 0x86, 0xc5, 0x6a, 0x26, 0x85, 0xfb, 0x24,
	0x8b, 0x8f, 0x00, 0x53, 0x52, 0xf3, 0x2e, 0xf4, 0xd9, 0xd6, 0xd6, 0x1a, 0x26, 0x27, 0x5b, 0x30,
	0x2b, 0x97, 0xac, 0x97, 0xdf, 0xc3, 0xb5, 0xd0, 0x69, 0x65, 0x4d, 0x99, 0xd2, 0x0f, 0xaf, 0x8d,
	0x24, 0x17, 0xba, 0xf2, 0xf8, 0x35, 0x2b, 0xfe, 0x86, 0x22, 0x9a, 0xf5, 0x3d, 0x79, 0xf8, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x91, 0xff, 0x5c, 0x44, 0x87, 0x01, 0x00, 0x00,
}
